//! The assembly layer — what typebridge actually owns.
//!
//! Per-type renderers ([`ts-rs`], [`specta`], …) lower one type at a time. A
//! [`Bridge`] is the orchestrator above them: it collects declarations and command
//! wrappers, stamps a generated-file header, optionally emits the `assertNever`
//! exhaustiveness helper, and renders one deterministic, formatted file. The same
//! value can then [`Rendered::write`] it or [`Rendered::check`] it against the
//! committed copy in CI.
//!
//! [`ts-rs`]: https://github.com/Aleph-Alpha/ts-rs
//! [`specta`]: https://github.com/specta-rs/specta

use std::fs;
use std::io;
use std::path::Path;

use crate::check::CheckOutcome;
use crate::command::{Command, Transport};
use crate::ir::Decl;

/// The default header stamped onto generated files. Mirrors the convention the
/// irodori desktop app already uses for its `ts-rs` output, so a swap to
/// typebridge is invisible to readers of the file.
const DEFAULT_HEADER: &str = "// @generated by typebridge. Do not edit.";

/// The standard exhaustiveness guard. A `default:` branch that calls this fails to
/// type-check the moment a new union variant is added but left unhandled — the
/// TypeScript echo of PureScript/Elm totality.
const ASSERT_NEVER: &str = "\
/**
 * Exhaustiveness guard for closed unions. Use in a `default` branch:
 *   default: return assertNever(x);
 * Adding a variant without handling it then becomes a compile error.
 */
export function assertNever(value: never): never {
  throw new Error(\"Unhandled union variant: \" + JSON.stringify(value));
}
";

/// A builder that assembles declarations and commands into one TypeScript module.
#[derive(Clone, Debug)]
pub struct Bridge {
    transport: Transport,
    header: String,
    decls: Vec<Decl>,
    commands: Vec<Command>,
    emit_assert_never: bool,
}

impl Bridge {
    /// A bridge targeting a given transport, with the default header.
    pub fn new(transport: Transport) -> Self {
        Bridge {
            transport,
            header: DEFAULT_HEADER.to_string(),
            decls: Vec::new(),
            commands: Vec::new(),
            emit_assert_never: false,
        }
    }

    /// A bridge whose commands render as Tauri `invoke` wrappers.
    pub fn tauri() -> Self {
        Bridge::new(Transport::Tauri)
    }

    /// A bridge whose commands render as transport-agnostic `request` wrappers.
    pub fn fetch() -> Self {
        Bridge::new(Transport::Fetch)
    }

    /// Override the generated-file header (provide the comment text *without* a
    /// trailing newline; lines are emitted verbatim).
    pub fn header(mut self, header: impl Into<String>) -> Self {
        self.header = header.into();
        self
    }

    /// Add a declaration. Takes a reference and clones, so the same [`Decl`] can be
    /// reused across bridges (e.g. an app bridge and an extension-SDK bridge).
    pub fn decl(mut self, decl: &Decl) -> Self {
        self.decls.push(decl.clone());
        self
    }

    /// Add several declarations.
    pub fn decls<'a, I>(mut self, decls: I) -> Self
    where
        I: IntoIterator<Item = &'a Decl>,
    {
        self.decls.extend(decls.into_iter().cloned());
        self
    }

    /// Add a command wrapper.
    pub fn command(mut self, command: Command) -> Self {
        self.commands.push(command);
        self
    }

    /// Emit the `assertNever` exhaustiveness helper at the end of the module.
    pub fn with_assert_never(mut self, enabled: bool) -> Self {
        self.emit_assert_never = enabled;
        self
    }

    /// Render the assembled module into a [`Rendered`] value.
    pub fn render(&self) -> Rendered {
        // Blocks are joined with a single blank line between them.
        let mut blocks: Vec<String> = Vec::new();

        blocks.push(self.header.clone());

        if !self.commands.is_empty() {
            if let Some(import) = self.transport.import_line() {
                blocks.push(import.to_string());
            }
        }

        for decl in &self.decls {
            // Each decl already ends in a newline; trim it so the join controls spacing.
            blocks.push(decl.render().trim_end().to_string());
        }

        for command in &self.commands {
            blocks.push(command.render(self.transport).trim_end().to_string());
        }

        if self.emit_assert_never {
            blocks.push(ASSERT_NEVER.trim_end().to_string());
        }

        // One trailing newline; deterministic and formatter-friendly.
        let contents = format!("{}\n", blocks.join("\n\n"));
        Rendered { contents }
    }
}

/// The rendered TypeScript module, plus the verbs to persist or verify it.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct Rendered {
    /// The full file contents, terminated by a single newline.
    pub contents: String,
}

impl Rendered {
    /// Write the contents to `path`, creating parent directories as needed.
    pub fn write(&self, path: impl AsRef<Path>) -> io::Result<()> {
        let path = path.as_ref();
        if let Some(parent) = path.parent() {
            if !parent.as_os_str().is_empty() {
                fs::create_dir_all(parent)?;
            }
        }
        fs::write(path, &self.contents)
    }

    /// Compare the contents against the file at `path` without writing.
    ///
    /// Returns [`CheckOutcome::Missing`] if the file is absent,
    /// [`CheckOutcome::UpToDate`] if it matches, or [`CheckOutcome::Drift`] with
    /// the first differing line otherwise.
    pub fn check(&self, path: impl AsRef<Path>) -> io::Result<CheckOutcome> {
        let path = path.as_ref();
        let path_str = path.display().to_string();
        match fs::read_to_string(path) {
            Ok(actual) => Ok(CheckOutcome::compare(
                &path_str,
                &self.contents,
                Some(&actual),
            )),
            Err(e) if e.kind() == io::ErrorKind::NotFound => {
                Ok(CheckOutcome::compare(&path_str, &self.contents, None))
            }
            Err(e) => Err(e),
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::command::Arg;
    use crate::ir::TsType;

    #[test]
    fn doc_example_renders_alias_and_command() {
        let status = Decl::alias(
            "ConnectionStatus",
            TsType::string_literals(["connected", "idle"]),
        );
        let ts = Bridge::tauri()
            .decl(&status)
            .command(Command::new("workspace_snapshot", "WorkspaceSnapshot"))
            .render();

        assert!(
            ts.contents
                .contains("export type ConnectionStatus = \"connected\" | \"idle\";"),
            "{}",
            ts.contents
        );
        assert!(
            ts.contents
                .contains("export function workspaceSnapshot(): Promise<WorkspaceSnapshot>"),
            "{}",
            ts.contents
        );
        // Header is present and the Tauri import is pulled in because there is a command.
        assert!(ts
            .contents
            .starts_with("// @generated by typebridge. Do not edit."));
        assert!(ts
            .contents
            .contains("import { invoke } from \"@tauri-apps/api/core\";"));
        // Exactly one trailing newline.
        assert!(ts.contents.ends_with("}\n"));
        assert!(!ts.contents.ends_with("\n\n"));
    }

    #[test]
    fn no_import_without_commands() {
        let status = Decl::alias("Status", TsType::string_literals(["a"]));
        let ts = Bridge::tauri().decl(&status).render();
        assert!(!ts.contents.contains("import"), "{}", ts.contents);
    }

    #[test]
    fn assert_never_is_opt_in() {
        let off = Bridge::tauri().render();
        assert!(!off.contents.contains("assertNever"));
        let on = Bridge::tauri().with_assert_never(true).render();
        assert!(on
            .contents
            .contains("export function assertNever(value: never): never"));
    }

    #[test]
    fn render_is_deterministic() {
        let build = || {
            Bridge::tauri()
                .decl(&Decl::interface(
                    "Q",
                    [crate::ir::Field::rust("connection_id", TsType::string())],
                ))
                .command(
                    Command::new("run_query", "QueryResult")
                        .arg(Arg::rust("connection_id", TsType::string())),
                )
                .render()
        };
        assert_eq!(build(), build());
    }

    #[test]
    fn write_then_check_round_trips() {
        let dir = std::env::temp_dir().join("typebridge-bridge-test");
        let path = dir.join("api.ts");
        let rendered = Bridge::tauri()
            .command(Command::new("ping", "boolean"))
            .render();

        rendered.write(&path).expect("write");
        let outcome = rendered.check(&path).expect("check");
        assert!(outcome.is_up_to_date(), "{}", outcome.summary());

        // Mutate the file on disk; the check must now report drift.
        std::fs::write(&path, "// tampered\n").expect("tamper");
        let drift = rendered.check(&path).expect("check");
        assert!(!drift.is_up_to_date());

        let _ = std::fs::remove_dir_all(&dir);
    }
}
