//! Coordination test: reproduce the irodori-table boundary with typebridge.
//!
//! The consumer (`irodori-table/apps/desktop`) currently generates its frontend
//! boundary with `ts-rs` into `src/generated/irodori-api.ts`. This test models the
//! exact same domain — `DbObjectKind`, `ConnectionStatus`, `DbObject`,
//! `Connection`, `WorkspaceSnapshot`, and the `workspace_snapshot` command —
//! through typebridge's IR, and asserts the generated surface is type-compatible.
//!
//! It is the executable contract behind `docs/irodori-typebridge-handoff.md`: if
//! typebridge is ever wired into irodori, this is the shape it must emit.

use typebridge::ir::{Decl, Field, TsType};
use typebridge::{Bridge, Command};

/// Build the irodori boundary as a single rendered module.
fn render_irodori() -> String {
    // Sum types -> closed unions.
    let db_object_kind = Decl::alias(
        "DbObjectKind",
        TsType::string_literals(["table", "view", "procedure"]),
    );
    let connection_status = Decl::alias(
        "ConnectionStatus",
        TsType::string_literals(["connected", "idle"]),
    );

    // Product types -> interfaces. `rows` is an `Option<String>` that may be
    // absent on the wire, so it is an optional key.
    let db_object = Decl::interface(
        "DbObject",
        [
            Field::rust("name", TsType::string()),
            Field::rust("kind", TsType::named("DbObjectKind")),
            Field::rust("rows", TsType::string()).optional(),
        ],
    );
    let connection = Decl::interface(
        "Connection",
        [
            Field::rust("id", TsType::string()),
            Field::rust("name", TsType::string()),
            Field::rust("engine", TsType::string()),
            Field::rust("status", TsType::named("ConnectionStatus")),
            Field::rust("latency_ms", TsType::number()),
            Field::rust("proxy", TsType::string()),
            Field::rust("objects", TsType::array(TsType::named("DbObject"))),
        ],
    );
    let workspace_snapshot = Decl::interface(
        "WorkspaceSnapshot",
        [
            Field::rust("connections", TsType::array(TsType::named("Connection"))),
            Field::rust("active_connection_id", TsType::string()),
        ],
    );

    Bridge::tauri()
        .decl(&db_object_kind)
        .decl(&connection_status)
        .decl(&db_object)
        .decl(&connection)
        .decl(&workspace_snapshot)
        .command(Command::new("workspace_snapshot", "WorkspaceSnapshot"))
        .render()
        .contents
}

#[test]
fn reproduces_irodori_boundary() {
    let ts = render_irodori();

    // Header + transport import, matching the existing generated file's intent.
    assert!(ts.starts_with("// @generated by typebridge. Do not edit."));
    assert!(ts.contains("import { invoke } from \"@tauri-apps/api/core\";"));

    // Closed unions for the enums (totality preserved).
    assert!(ts.contains("export type DbObjectKind = \"table\" | \"view\" | \"procedure\";"));
    assert!(ts.contains("export type ConnectionStatus = \"connected\" | \"idle\";"));

    // snake_case Rust fields surfaced as camelCase wire names.
    assert!(ts.contains("latencyMs: number;"), "{ts}");
    assert!(ts.contains("activeConnectionId: string;"), "{ts}");

    // Option<String> -> optional key, not `string | null`.
    assert!(ts.contains("rows?: string;"), "{ts}");

    // Vec<T> -> T[].
    assert!(ts.contains("objects: DbObject[];"), "{ts}");
    assert!(ts.contains("connections: Connection[];"), "{ts}");

    // Typed command wrapper: camelCase fn name, snake_case invoke key.
    assert!(ts.contains("export function workspaceSnapshot(): Promise<WorkspaceSnapshot> {"));
    assert!(ts.contains("return invoke(\"workspace_snapshot\");"));
}

#[test]
fn output_is_deterministic() {
    assert_eq!(render_irodori(), render_irodori());
}
